language: c

python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      - libzmq3-dev

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

  - luarocks show lluv         || bash .travis/setup_uv.sh
  - luarocks show lluv         || luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks show tpdu         || luarocks install tpdu         --from=https://luarocks.org/dev
  - luarocks show rs232        || luarocks install rs232        --from=https://luarocks.org/dev
  - luarocks show lluv-rs232   || luarocks install lluv-rs232   --from=https://luarocks.org/dev
  - luarocks show EventEmitter || luarocks install EventEmitter --from=https://luarocks.org/dev

install:
  - luarocks make rockspecs/lluv-gsmmodem-scm-0.rockspec

before_script:
  - luarocks show lunitx           || luarocks install lunitx
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls

script:
  - cd test
  - lunit.sh test_modem.lua
  - lunit.sh test_commander.lua

after_success:
  - luacov-coveralls -v

notifications:
  email:
    on_success: change
    on_failure: always
