language: c

python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      - libzmq3-dev

env:
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  - luarocks show lluv > /dev/null 2>&1 || bash .travis/setup_uv.sh

install:
  - luarocks make rockspecs/lluv-gsmmodem-scm-0.rockspec UV_DIR=$TRAVIS_BUILD_DIR/libuv

before_script:
  - luarocks show lunitx           > /dev/null 2>&1 || luarocks install lunitx
  - luarocks show cluacov          > /dev/null 2>&1 || luarocks install cluacov
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls

script:
  - cd test
  - lunit.sh test_modem.lua
  - lunit.sh test_commander.lua

after_success:
  - luacov-coveralls -v

before_cache:
  - luarocks remove lluv-gsmmodem
  - rm -f /home/travis/.cache/pip/log/debug.log

notifications:
  email:
    on_success: change
    on_failure: always
